/********************************************************************
* eventdict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error eventdict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableeventdict();
extern void G__cpp_setup_inheritanceeventdict();
extern void G__cpp_setup_typetableeventdict();
extern void G__cpp_setup_memvareventdict();
extern void G__cpp_setup_globaleventdict();
extern void G__cpp_setup_memfunceventdict();
extern void G__cpp_setup_funceventdict();
extern void G__set_cpp_environmenteventdict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "Analysis/NtupleProducer/interface/myobject.h"
#include "Analysis/NtupleProducer/interface/myevent.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__eventdictLN_TClass;
extern G__linked_taginfo G__eventdictLN_TBuffer;
extern G__linked_taginfo G__eventdictLN_TMemberInspector;
extern G__linked_taginfo G__eventdictLN_TObject;
extern G__linked_taginfo G__eventdictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__eventdictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__eventdictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__eventdictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__eventdictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__eventdictLN_myobject;
extern G__linked_taginfo G__eventdictLN_maplEstringcOintcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOintgRsPgRsPgR;
extern G__linked_taginfo G__eventdictLN_myGenobject;
extern G__linked_taginfo G__eventdictLN_myevent;
extern G__linked_taginfo G__eventdictLN_vectorlEmyobjectcOallocatorlEmyobjectgRsPgR;
extern G__linked_taginfo G__eventdictLN_vectorlEmyobjectcOallocatorlEmyobjectgRsPgRcLcLiterator;
extern G__linked_taginfo G__eventdictLN_reverse_iteratorlEvectorlEmyobjectcOallocatorlEmyobjectgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__eventdictLN_vectorlEmyGenobjectcOallocatorlEmyGenobjectgRsPgR;
extern G__linked_taginfo G__eventdictLN_vectorlEmyGenobjectcOallocatorlEmyGenobjectgRsPgRcLcLiterator;
extern G__linked_taginfo G__eventdictLN_reverse_iteratorlEvectorlEmyGenobjectcOallocatorlEmyGenobjectgRsPgRcLcLiteratorgR;

/* STUB derived class for protected member access */
typedef vector<myobject,allocator<myobject> > G__vectorlEmyobjectcOallocatorlEmyobjectgRsPgR;
typedef vector<myobject,allocator<myobject> >::iterator G__vectorlEmyobjectcOallocatorlEmyobjectgRsPgRcLcLiterator;
typedef vector<myGenobject,allocator<myGenobject> > G__vectorlEmyGenobjectcOallocatorlEmyGenobjectgRsPgR;
typedef vector<myGenobject,allocator<myGenobject> >::iterator G__vectorlEmyGenobjectcOallocatorlEmyGenobjectgRsPgRcLcLiterator;
